# -*- coding: utf-8 -*-
"""INFO450StreamlitApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17WPI9Px1W0M6890fIXRv5C2W0K9wMEM8
"""

import streamlit as st
import pandas as pd
import plotly.express as px

df = pd.read_csv('Advertising_F.csv')

st.title('Advertising Effectiveness Jasmin')
st.sidebar.header('Filters')
x_var = st.sidebar.selectbox('X Axis', ['TV', 'radio', 'newspaper'])
y_var = st.sidebar.selectbox('Y Axis', ['sales'])

# show scatterplot
fig = px.scatter(df, x = x_var, y = y_var)
st.plotly_chart(fig)

#Dataframe
st.write('###This is the data')
st.dataframe(df)

#Show map
st.title('Map')
fig = px.scatter_mapbox(df, lat = 'latitude', lon = 'longitude',
                        size = 'newspaper', hover_name = 'City',
                        color = 'sales',
                        color_continuous_scale = px.colors.sequential.Viridis)
fig.update_layout(mapbox_style = 'carto-positron')
st.plotly_chart(fig)